name: Build rule sets

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'scripts/build.mjs'
      - '.github/workflows/build-release.yml'
      - '.github/workflows/publish-release.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/publish-release.yml
    with:
      source-ref: main
